### ISSUE TITLE
Clear alby text after boost is completed

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-web#1013]
**Clear alby text after boost is completed**
After submitting a boost I expect the message box should be cleared out.

**To Reproduce**
1. Enter a boost message via Alby on the website form
2. Click on 'Send Boost'
3. See message still there

**Expected behavior**
The text should be cleared as if sent to the podcast

**Desktop (please complete the following information):**
 - Browser Firefox

**Comment by mitchdowney** [comment]
also this change was in release 33 of webln-v4v 👀 https://github.com/podverse/webln-v4v/commit/90bcb4dd799864a143a29b21c3fb13a0f946ed4b
