### ISSUE TITLE
UX: unavailable episode limit option not grayed out

### ISSUE THREAD

**Issue by comradekingu** [podverse/podverse-web#1027]
"Default downloaded episode limit for each podcast"
in Settings → Downloads

This is the number selection of the above entry, which says the same thing already.
It could be made "Limit:" if it was more clear the two belonged together.

**Comment by mitchdowney** [comment]
I updated the More > Settings > Downloads screen to say "Limit". This should be in v4.7.1.

![CleanShot 2022-11-27 at 22 06 36](https://user-images.githubusercontent.com/2262919/204193631-935fb49b-3df4-4590-97c1-0251ffd18802.gif)

I think this Github issue was meant for podverse-rn? That's the mobile app repo :)

https://github.com/podverse/podverse-rn/commit/e208130472df625bed4f68d4cf16e9e5193b5723

**Comment by comradekingu** [comment]
@mitchdowney 
Great :)
