### ISSUE TITLE
When no matching data in transcript, search bar disappears

### ISSUE THREAD

**Issue by stevencrader** [podverse/podverse-web#1034]
**Describe the bug**
When searching a transcript, if the search phrase is not found, the search box disappears so you cannot continue searching.

**To Reproduce**
1. Go to https://podverse.fm/episode/LFPmBNRwR
2. Click on "Transcript"
3. Enter a search term that is not in the transcript (ex: "zzz")
4. Notice the search box disappears

**Expected behavior**
Search box stays so the search phrase can be modified.

**Screenshots**
No search phrase: 
![image](https://user-images.githubusercontent.com/677342/202835227-8716b4d8-eaad-4f8d-b22f-d826c6629751.png)

Searching for "zzz"
![image](https://user-images.githubusercontent.com/677342/202835239-9d7b0129-0b05-4c10-a2c5-46c88e6c5f57.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 107.0.5304.107 (Official Build) (64-bit)

**Additional context**
The issue seems to be caused by the `SearchBarFilter` only being shown when `transcriptRowNodes` contains more than 1 item. See https://github.com/podverse/podverse-web/blob/f703a1f56147f1b0ac0a5814e2abd27ffc11f03f/src/components/Transcripts/Transcripts.tsx#L160-L167

**Comment by mitchdowney** [comment]
@stevencrader good catch! Added a small change to state to fix this. Deploying now...

**Comment by mitchdowney** [comment]
@stevencrader should be fixed and deployed. If you can verify it when you get a chance and close this issue if it works I'd appreciate it.

**Comment by stevencrader** [comment]
Issue no longer occurs
