### ISSUE TITLE
Episodes missing

### ISSUE THREAD

**Issue by Creat1veM1nd** [podverse/podverse-web#1196]
Hello, 

not sure if this is a bug, so I thought I post it in "other".

This podcast: https://feeds.acast.com/public/shows/651d41a8b1175d0011545cf4 has it's last episode a few days ago. But on web and also android app (on 2 different phones) only one episode from 16th January 2023 is shown. I tried to remove and add the podcast again, but with no luck. Any hint what could cause this and how to fix it ?

Thanks in advance!

**Comment by mitchdowney** [comment]
Hi @Creat1veM1nd, I just created an [FAQ answer](https://github.com/orgs/podverse/discussions/12#discussioncomment-7191411) for this question. Please check it out when you have a chance.

In this case, the Aktenzeichen Paranormal was _completely missing_ from Podcast Index, but _present_ in Podverse. As a result, Podverse stopped receiving "new episode" notifications from Podcast Index, so our servers did not re-parse it.

This is actually a trickier edge case. Usually this problem doesn't happen. We would typically recommend emailing contact@podverse.fm and reporting the issue for us to resolve it. In any case, I went ahead and resolved the issue. Unfortunately the previous URL to the podcast on Podverse is broken now, but you can find the new page [here](https://podverse.fm/podcast/MFWooQMR7S).

Please let me know if you have any other questions, and close this issue if this is resolved for you. Thanks!
