### ISSUE TITLE
Dropdown menu in episodes queue shows below the episode description

### ISSUE THREAD

**Issue by tmorgan497** [podverse/podverse-web#1206]
**Describe the bug**
Dropdown menu on episodes in the queue sometimes show below the episode description, causing the user to click on the episode instead of the menu item

**To Reproduce**
1. Go to ['Queue'](https://podverse.fm/queue)
2. Click on the more button (`ellipsis-h`)
3. Click on an item in the menu
   - If the episode under the menu is showing through, the user will actually click on the episode link instead of the menu item
5. See error

**Expected behavior**
The 'more' menu should be in front of the episode description or disallow click passthrough

**Screenshots**
![image](https://github.com/podverse/podverse-web/assets/21185911/3eda2794-36c0-4842-bb5e-8280836c1be4)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox and Microsoft Edge
 - Version: Firefox[118.0.2], Edge[118.0.2088.61]

**Smartphone (please complete the following information):**
 - N/A

**Comment by mitchdowney** [comment]
@tmorgan497 oh I hadn't seen that. Hmm should be a simple CSS fix I think. I wonder why the issue happens on the Queue screen, but nowhere else on the website that use the same episode rows?

**Comment by tmorgan497** [comment]
Honestly, the queue page is the only place I've looked so far 🙃. I did peruse the codebase a bit to see if I could find a culprit but I'm not familiar with this framework. I've mainly dabbled in Vue.js and Django. I'll keep poking around and see if it occurs elsewhere.

**Comment by p4p4j0hn** [comment]
This only happens when the menu drops down from the elipsis, when it pops upward from the elipsis the component is in the foreground with an opaque background and all the buttons are selectable.

**Comment by p4p4j0hn** [comment]
Dropdown is quite nested on the queue page. Probably why it gets clobbered a bit. No other page has the draggable list. That's the only difference I can see really. `react-draggable-list` might be affecting things.
