### ISSUE TITLE
Mixed content in firefox

### ISSUE THREAD

**Issue by fabianski7** [podverse/podverse-web#164]
**Steps to reproduce**
1. In the url bar, go to about:config
2. Change the preference `security.mixed_content.block_display_content` to `true`
3. Restart the browser
4. Try listening to some podcast with an insecure url ([like this one](https://podverse.fm/episode/r_kszhopT))

The firefox console will return this
`Blocked loading mixed display content “http://feeds.soundcloud.com/stream/898306954-tecnoblog-162-duelo-de-gigantes.mp3”r_kszhopT`

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

Since soundcloud has a TLS certificate, it is possible to redirect access to the secure version by replacing the url for https. This should be what you can do in these cases.

**Comment by mitchdowney** [comment]
Hey thanks for letting us know! So in the mobile app we're just switching URLs with HTTP protocol to HTTPS, because iOS and (I think) Android are blocking insecure protocol requests by default. I guess we should just replace all HTTP links to HTTPS in the web browser? And if people are sharing content over HTTP, oh well? Not sure if that's the ideal way to fix it, but I could get it done this week.

**Comment by fabianski7** [comment]
Maybe you can do this redirect only to known domains, like spotify, soundcloud, castbox, anchor.fm, feedburner, etc.

This is not a problem that will affect many people, since this preference is disabled by default in firefox, but the user will receive an alert that they are loading mixed content.

**Comment by mitchdowney** [comment]
@fabianski7 I tried implementing a fix like you described. Mike Kelley from [podcastranking.com](podcastranking.com) and the [Podcast Index Mastodon](https://podcastindex.social/) channel provided the "most used media file domains" list.

According to my test it appears to have fixed the issue with [the Tecnocast episode](https://podverse.fm/episode/r_kszhopT). If you could test it out sometime and let us know how it goes I'd really appreciate it.

Relevant commits:
https://github.com/podverse/podverse-shared/commit/ce526025f263e037c3170a6c898c0def55b5d3e4#diff-afc90cc9022ffdf3e50246d94d93278eR14

https://github.com/podverse/podverse-web/commit/b972d9580004a676c87f4d7da261805af9542de0#diff-0c630cb67042dbeb6898d0a4f45f0c09R1

**Comment by fabianski7** [comment]
thanks! working fine now!
