### ISSUE TITLE
Unable to retry send verification email 

### ISSUE THREAD

**Issue by Siebe** [podverse/podverse-web#170]
When I as a new user try to register on the website, but I think I misspelled my email, I would like to retry sending a verification email. However, when I try to click on "Sign up" again, I only get a message I should verify email.

Very small issue and can be easily resolved by refresh. However I'm reporting because I'm afraid it might be a barrier when people try to sign up (and be like me, an idiot who sometimes misspells his email).

**Comment by mitchdowney** [comment]
@Siebe ahh that's definitely not an intended behavior.

This was actually just a one-line change https://github.com/podverse/podverse-web/pull/171/commits/9e74e774982a294454d441aec578ed2f67510a0f

Thanks so much again for sharing these UX improvements! These kinds of changes take very little time to do but can go a long way with new users. We obviously don't want to scare people away the first time they try using the site.

**Comment by Siebe** [comment]
Check, works nice.  I hit a rate limit after 2 tries, but that seems reasonable. If one can not write their email correctly 2 times, you should wait 2 minutes.
