### ISSUE TITLE
Handle when an episode previously in a feed is no longer available in the feed

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#18]
Not the priority right now, but something to be aware of because this use case is pretty common. 

[Dan Carlin's Hardcore History](http://feeds.feedburner.com/dancarlin/history?format=xml) provides the last 10 episodes for free, but anything before that goes behind a paywall.

Maybe we can detect when an episode's mediaURL and/or GUID is no longer in a feed, then if someone tries to access a clip based on that episode, we display a "this is clip is no longer available message"? Maybe with some more details to explain why this happens from time to time.

Even if we could give subscribing users access to the episode behind the paywall, maybe we can't assume the mp3s are still identical and therefore the clip metadata is no longer valid.

**Comment by scvnc** [comment]
The clip data could be useful, especially if there is a title/description.  If it cant be played then show the message with the whole explanation of why this may happen
