### ISSUE TITLE
Set duration in the templates

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#19]
Previously in NeDB we passed duration as a property of Clip, along with startTime and endTime, but this time I was thinking we should instead set duration as a fake (?) property of Clip, retrieved through a getter method or something.

**Comment by mitchdowney** [comment]
It's a bug bc duration isn't showing up where expected in the templates

**Comment by scvnc** [comment]
We probably don't want `duriation` because that is a unecessary redundancy.  I would instead opt for whatever is consuming the clip (iOS, nunjucks/javascript) to calculate it when needed (endTime-startTime)
