### ISSUE TITLE
Associate playlists and users to know which playlists a user is subscribed to

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#21]
There seems to be a broader story here about enabling the app to save properties to the User object. 

[This example](https://github.com/feathersjs/feathers-demos/tree/master/examples/authentication/auth0) might be handy.

**Comment by scvnc** [comment]
I've seen that example and it focuses on an older use case with Auth0.  A local user object could probably be made that matches up with the `sub` value of the token.

I'm pretty keen on just having a list of playlist urls/ids stored client side.  The list could be dumped into a json blob in the user table if necessary.

**Comment by mitchdowney** [comment]
Ah ok. So would that be something I could download locally? Like a Save As or Download button, so we can keep a backup file of the playlists I'm subscribed to?

**Comment by scvnc** [comment]
Is it podverse's responsibility to host a subscribed set of playlists?  Maybe.

It is rarely ever a podcast app's responsibility to save the podcasts you've subscribed to. 

The user table, as we discussed on whatsapp, could store a list of playlist ids, if we really want to do this.  It's 'nice' but I'm always trying to evaluate whether such a feature would make the service too monolithic.  Hurling around URLs and stuff decouples podverse from the iOS app in a nice way.  You could export the playlist ids to a file on your iPhone or email the list to yourself as an alternative.

**Comment by mitchdowney** [comment]
Ok gotcha and agreed on avoiding monolithic app.

I guess what pushes me towards a My Podcasts backup feature is, as a not-very-good iOS developer, I find myself deleting/reinstalling the app more than an avg app user would. Whenever that happens, my subscribed podcasts list gets wiped out, and it's onerous for me to remember, search for, and then resubscribe to them each time. That's primarily the problem I'm looking to solve...

**Comment by scvnc** [comment]
You could have the ability to "backup"/" load" your saved user data to iOS
storage or ship it off to the user enndpoint

**Comment by mitchdowney** [comment]
Manually saving a "backup" of my podcasts and playlists would be an improvement, but I'd really like the app to just show me my podcasts and playlists as soon as I login. The process of saving and loading a file on a mobile device sounds like an unnatural mobile UX to me. Plus, I would have to remember to save a new backup every time I add or remove a podcast or playlist, which is something I do pretty frequently, so that would get tedious. 

I really dread the thought of losing my comprehensive list of podcasts again...

If I were to implement saving on server, I am thinking I could create a User model with the following properties:

**User Model**
userId: primary key, equals the userId provided by Auth0
followedPodcasts: array of podcast feedURLs
followedPlaylists: array of playlist ids

It seems to me that when Auth0 creates a new user object, before it responds to the client saying the sign-up was successful, Auth0 would need to post the new userId to podverse-web, then podverse-web would have to tell Auth0 when the user instance was created successfully, then Auth0 could respond with the userId to the client who requested it. If this is a viable approach, currently I have no idea how to get Auth0 and podverse-web to communicate like this after an Auth0 signup...some kind of Auth0 sign-up callback setup?

With this approach I'd have to make a User Service to handle creating and updating user objects. Creating user objects should only be permitted to requests by Auth0 (maybe by checking for a valid JWT), and updating a user object should only be permitted to the owner of that user object.

Do you think that's feasible? Problematic?
