### ISSUE TITLE
CORS Problem while trying to playback Podcasts on Web (and iOS app)

### ISSUE THREAD

**Issue by Muppet1856** [podverse/podverse-web#236]
Cannot play The Megyn Kelly Show or Security Now (TWiT).

**Comment by mitchdowney** [comment]
@Muppet1856 thanks for reporting and sorry for the delay!

Using Mac OSX Big Sur and the Brave browser, I was just able to play both [The Megyn Kelly Show](https://podverse.fm/episode/7XNFYgRq_) and [Security Now (Audio)](https://podverse.fm/episode/woDlJfCd2) on the Podverse website without a CORS issue.

What OS and browser combination are you using? And can you link me to a specific episode that gives you the CORS issue?

**Comment by Muppet1856** [comment]
This issue resolved. I assume it’s because something changed in the feed.
