### ISSUE TITLE
Set links in show notes to open to not disrupt the app playback

### ISSUE THREAD

**Issue by djbrieck** [podverse/podverse-web#240]
If a link in show notes is clicked the link disrupts the web app by going to a new page as referenced. This should probably open in a new tab etc.

eg probably need to add something something like the following: target="_blank" rel="noopener noreferrer" to the a tags in show notes section.

![click link and leave Podverse example ](https://user-images.githubusercontent.com/16352991/111714417-d4709600-880e-11eb-98a7-3a73ce6a754e.png)

**Comment by mitchdowney** [comment]
@djbrieck thanks for reporting this! It's a great idea. I went ahead and made the change to our component library, and re-deployed the website. Please give the new links a try when you have a chance.

https://github.com/podverse/podverse-ui/commit/0da598eb86c3068370b094cfd0bdcd77512c320e

**Comment by djbrieck** [comment]
@mitchdowney just checked now, external links are opening in a new tab. Thanks
