### ISSUE TITLE
Help improve our usage of TypeScript types

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#288]
The Podverse repos are the first project @kreonjr and I have ever used TypeScript types in, and we have not consistently followed good practices. For example, there is gratuitous use of the `any` type throughout the code 😬 

If you can help us with writing proper types anywhere in the code, or improving our TypeScript usage in any way, we would greatly appreciate it.

Even if you make an improvement in just a few places, we may be able to follow the example of your code and apply it in many more places across the app.

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by Samikmalhotra** [comment]
hey, can I work on this?

**Comment by mitchdowney** [comment]
@Samikmalhotra hello! Yes you may! I'll assign the issue to you.

If you have any questions please let me know. We could schedule a time to pair if you would like. Thanks for your help!

**Comment by mitchdowney** [comment]
Hey @Samikmalhotra do you have any ideas how to fix this issue? I'm confused because `pageKey` is already a prop on the NavBar component, but the prop seems to be getting flagged and throwing an error anyway...

![image](https://user-images.githubusercontent.com/2262919/135765726-8d5d22ce-4340-47d0-a256-814d38b8acf7.png)

![image](https://user-images.githubusercontent.com/2262919/135765735-c0467f2c-4089-4172-bb62-e798ae9da388.png)

**Comment by mitchdowney** [comment]
Actually, I am able to reproduce this issue when i run `yarn` and then `yarn dev`, but I'm not able to reproduce the issue when I run `npm install` and `npm run dev`, so maybe this is just a local environment issue 🤷‍♂️

**Comment by Samikmalhotra** [comment]
i'm glad that it worked

**Comment by Samikmalhotra** [comment]
hi mitch, unfortunately im not able to devote time to the project and it is my humble request to unassign me from the issue and let someone more experienced take a look at it. Your project is amazing and really advanced, i'm a beginner so i'll try to gain some more experience and contribute to podverse. In the meantime i'll try to understand all of the code and look for future opportunities to contribute to podverse. Thank you

**Comment by mitchdowney** [comment]
@Samikmalhotra no worries! Thanks for checking out the project. If you ever want a tour of the Podverse ecosystem for educational purposes just let me know.

**Comment by Samikmalhotra** [comment]
Thank you so much!
