### ISSUE TITLE
Figure out how to efficiently derive total number of clips created for an episode

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#29]
If I'm on a podcast page and I see 50 episodes listed on the page, I want to see the total # of clips that have been created for each individual episode on that page.

I've tried a few times to come up with an efficient approach, but haven't figured it out yet. I think we might want to use a Sequelize getter method on the Episode model, but all my attempts have failed to make that work so far.

**Comment by scvnc** [comment]
http://docs.sequelizejs.com/en/latest/docs/models-usage/#count-count-the-occurrences-of-elements-in-the-database

MediaRefs.count({ where: ... episodeID == something})
