### ISSUE TITLE
Create a Footer component 

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#325]
Here's a screen shot of what the new Footer component should look like:

![image](https://user-images.githubusercontent.com/2262919/142292494-107226cd-2f6b-4548-ae0b-bbb5530d9302.png)

Pretty much like the old one, but with the logo image added.

![image](https://user-images.githubusercontent.com/2262919/142292822-61deb935-3aa3-4d7e-8fef-9b193e7dd585.png)

Make the page links, social media links, and Podcasting 2.0 Certified link work. If you're not sure what the URL should be you can just use https://podverse.fm for now and we could update them later.

Use CSS flex box rules for the component design, and bonus points if you make the footer responsive, so that when on a smaller width screen the links stack into horizontal components like the screenshot below:

![image](https://user-images.githubusercontent.com/2262919/142293092-486fbc6d-85a5-48ce-80c0-ae3d922d78e7.png)

**Comment by r1jsheth** [comment]
I would love to pick up this!

**Comment by mitchdowney** [comment]
You got it @r1jsheth! Thanks so much :)

**Comment by mitchdowney** [comment]
Hi @r1jsheth! Are you still available to work on this Footer component? If you are not available, @eurbasius might be interested in working on this feature.

**Comment by mitchdowney** [comment]
Hey @r1jsheth, @eurbasius is picking up this Footer component. If you'd ever like to work on another feature let us know. Thanks!

**Comment by r1jsheth** [comment]
Yeah, totally fine! I will be away for few days at least.
