### ISSUE TITLE
What's a good way to setup @podverse.fm email addresses?

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#35]
I followed the [steps to setup a Webfaction email](https://docs.webfaction.com/user-guide/email.html), and then I go to [Roundcube Webmail](https://webmail.webfaction.com/?_task=login) to login, but then my username and password doesn't work and I can't login.

It looks like I could setup @podverse.fm to import through a @gmail account, but I'd rather not have all mail go through a 3rd party if that's unnecessary.

Also, I'd like the webmail UX to be pretty simple for a non-developer to jump into. I thought Roundcube might be good enough but I can't login. Any other recommendations?

**Comment by scvnc** [comment]
put in a support ticket for webfaction-- if you're experiencing username/password issues then it is an issue with webfaction's service potentially.

**Comment by mitchdowney** [comment]
@scvnc Webfaction helped very quickly, and I can login and send outgoing mail from a podverse.fm email. There's a new issue though, note the question mark in the image below:

![image](https://cloud.githubusercontent.com/assets/2262919/21341578/e4d50418-c652-11e6-8b18-4b7ea3cb0455.png)

Apparently that is happening because the [email was not authenticated properly.](https://support.google.com/mail/answer/180707?authuser=1&visit_id=1-636178155140118139-448520328&p=email_auth&hl=en&rd=1)..ugh. Not sure what to make of all of it yet.

I didn't expect setting up a self-hosted email address to be this involved...

**Comment by scvnc** [comment]
email is hard because of all the anti-spam stuff-- lots of checks and balances-- I wonder if webfaction's email will be adequate

**Comment by mitchdowney** [comment]
Email is working properly now 👍
