### ISSUE TITLE
Weird inaccurate timestamp issue since switching to Postgres, timestamps seem to randomly increment

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#39]
@scvnc, do you know if I need to do any special timezone handling stuff to accurately store timestamps with Postgres?

Ever since switching to Postgres, when I make many clips for the same episode, the episodePubDate saved to those mediaRefs are incrementing. 

So clips from the same episode are storing episodePubDate as: 

1/5/17 10 PM
1/6/17 4 AM
1/6/17 4 AM
1/6/17 4 AM
1/6/17 10 AM 
1/6/17 10 AM 

They should of course all save identical episodePubDates, but instead they're randomly incrementing them by 6 hours.

I **thought** this was working fine in Sqlite3. Have you run across something like this with Postgres before?

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2262919/21756265/9c2d68bc-d5e4-11e6-95b8-df0c82601c7b.png)

**Comment by mitchdowney** [comment]
meant to put this in podcast-db

**Comment by mitchdowney** [comment]
Specifically this issue happened when creating clips for an episode of Duncan Trussell Family Hour http://feeds.feedburner.com/DuncanTrussell

**Comment by scvnc** [comment]
Nothing off the top of my head.

Troubleshooting instincts
  - observe the field type in postgres to see if it "makes sense" -- I expect it to be one of the `timestamp` types 
  - you can turn on sequilze's (debug?) mode which prints out every SQL statement it generates for postgres and examine that.  
  - Perhaps do some manual INSERT statements based on what we see from the other steps.

**Comment by mitchdowney** [comment]
Well I'll be. I can't recreate it anymore. I'll assume it magically fixed itself.
