### ISSUE TITLE
Playback Speed Setting not Preserved Between Episodes

### ISSUE THREAD

**Issue by FischerDavid** [podverse/podverse-web#471]
Playback speed reverts back to 1x speed after each episode while the playback indicator continues to display the speed of the last played episode.

1. Play an episode to completion a non-1x rate
2. Select another episode to listen to

**Expected Behavior**
I would prefer to have the playback speed remain consistent between episodes.  An alternative would be to update the playback interface to indicate 1x playback speed at the start of the next episode.

**Desktop**
 - OS: Manjaro KDE 5.23.4
 - Browser: Firefox 96

**Smartphone**
 - Device: iPhone SE
 - OS: iOS 15.2.1
 - Podverse Version: 4.2.0 Build 1192

**Comment by mitchdowney** [comment]
@FischerDavid I think I just fixed this bug on the website (haven't deployed yet but will in ~an hour), but I noticed you included:

> Podverse Version: 4.2.0 Build 1192

Did you run into this bug on the website (podverse-web) or the mobile app (podverse-rn)?
