### ISSUE TITLE
Episode Played Checkboxes not Displayed on Web Version

### ISSUE THREAD

**Issue by FischerDavid** [podverse/podverse-web#472]
**Describe the bug**
Episode Played checkmarks not displayed in the browser version of Podverse but are showing in the iOS version of the app

**To Reproduce**
1. Open up any Podcast with played episodes

**Expected behavior**
I would like to see the played checkmarks displayed similar to the iOS version.

**Desktop (please complete the following information):**
 - OS: Manjaro KDE 5.23.4
 - Browser Firefox 96

**Smartphone (please complete the following information):**
This is working on the iOS App

**Screenshot**
![No Checkmarks on Played Episodes](https://user-images.githubusercontent.com/46251310/149681950-5a21cff0-f51c-40b8-a650-aa324694901c.png)

**Comment by mitchdowney** [comment]
Green checkmarks should now be appearing for logged-in users. Hope this works for you!

![image](https://user-images.githubusercontent.com/2262919/150922603-c51b5248-af7c-40d0-b462-dc9ccd84e1e1.png)

**Comment by FischerDavid** [comment]
It is working, thank you so much!  This is a fantastic project!
