### ISSUE TITLE
Podcast episodes no longer marked as played

### ISSUE THREAD

**Issue by betsythefc** [podverse/podverse-web#713]
**Describe the bug**
A bunch of my podcasts that were marked as read, are no longer marked as played.

**To Reproduce**
I logged in today and found several podcasts of mine were no longer marked as played.

**Expected behavior**
Marked as played episodes to stay marked as played

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FIrefox
 - Version: 99.0.1

**Smartphone (please complete the following information):**
 - Device: Galaxy Z Flip 3 5G
 - OS: Android 12
 - Browser: F-Droid app
 - Version: 4.4.2

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
As I discussed with @betsythefc on Discord, it appears the issue happens for this podcast but not others:

"Beau of the Fifth Column"
RSS link: https://anchor.fm/s/cff1340/podcast/rss
Podverse link: https://podverse.fm/podcast/DuUN97wKm2

It could be that the episodeIds are getting changed for this feed every time it refreshes. If that's the case, then this could be a deep issue where we need to try to match history data with the new corresponding episodeIds.

**Comment by betsythefc** [comment]
As a heads up, my marked as played was reverted again.

Here is the URL for the most current episode. I've marked it as played.
https://anchor.fm/beau-of-the-fifth-column/episodes/Lets-talk-about-SCOTUS--dirty-little-secrets--and-hypocrisy-e1i1ag5
I see a hash-like tag put on the end of the URL: `e1i1ag5`.

Here is the guid: `<guid isPermaLink="false">df8ce727-c6d1-4365-bf15-0b0eeeeff7ea</guid>`
It does say it's not a permanent link...
I'll check the RSS again when it resets to see if either of these values change for this specific episode.

**Comment by mitchdowney** [comment]
@betsythefc sorry to hear that. This is a really deep issue to solve, because many podcasts do not properly assign GUIDs to their episodes, and our architecture is built around the assumption that we can't reliably assume GUIDs are unique and valid...we need to start migrating towards using episode GUIDs though since it's a better UX at least for the podcasts that use them correctly.

Anyway, are you still only seeing the issue for specific podcasts that maybe don't always use the same enclosure.url for episodes? Or does it seem like a broader issue with history disappearing for podcasts randomly?

**Comment by betsythefc** [comment]
It seems to be that specific podcast, and it hasn't yet happened. So if it is what we are thinking it is, it may be an adhoc reset of the hash-like addition to the episode names, something that isn't regular. Up to you if you want me to leave this open, or make a new one, assuming it happens again.

**Comment by mitchdowney** [comment]
@betsythefc we can leave this open because it relates to some Episode GUID problems that we need to solve sooner than later.

**Comment by mitchdowney** [comment]
The episode GUID problem was fixed a few months ago. I'm going to close this issue. If it resurfaces we can reopen and investigate it again.
