### ISSUE TITLE
Embedded  player: "About" link opens different overlays

### ISSUE THREAD

**Issue by kbondarev** [podverse/podverse-web#872]
"About" link drastically changes the player layout, doesn't offer an about page

**Describe the bug**
When using the embedded player the "About" link opens different overlay layouts (seems like the fullscreen view) and messes things up:

**To Reproduce**
1. Go to [here](https://jupiterbroadcasting.net/show/linux-unplugged/465/)
2. Scroll down to the player
3. Click on the "About" link
5. See error

**Expected behavior**
Open the https://podverse.fm/about page in a new tab

**Screenshots**
<kbd>![podverse bug - about](https://user-images.githubusercontent.com/7018928/180271088-d438d770-da93-4573-9a2a-d07591ad9502.gif)<kbd>

**Desktop (please complete the following information):**
 - OS: `Ubuntu 22.04`
 - Browser `brave`
 - Version  `1.41.96  Chromium: 103.0.5060.114 (Official Build)  (64-bit)`

**Additional context**
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/140

**Comment by mitchdowney** [comment]
Whoops! Used the wrong style of link tag (need to use an <a> tag with target="_blank". Thanks for the bug report.

Should be fixed in https://github.com/podverse/podverse-web/pull/876
