### ISSUE TITLE
Embedded player: "Open Source" link breaks player

### ISSUE THREAD

**Issue by kbondarev** [podverse/podverse-web#873]
**Describe the bug**
"Open Source" link fails to open inside the iframe, and in turn breaks the whole player UI.

**To Reproduce**
1. Go to [here](https://jupiterbroadcasting.net/show/linux-unplugged/465/)
2. Click on the "Open Source" in the player (bottom right corner)
3. See error

**Expected behavior**
The [link](https://jupiterbroadcasting.net/show/linux-unplugged/465/) should open in a new tab when the player is embedded inside an iframe.

**Screenshots**
<kbd>![podverse bug - open source](https://user-images.githubusercontent.com/7018928/180271363-88bdc490-5ad9-4f6d-97c6-4f2767d2ef23.gif)</kbd>

**Additional context**
[Add any other context about the problem here.](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/140)

**Comment by mitchdowney** [comment]
Whoops! Used the wrong style of link tag (need to use an <a> tag with target="_blank". Thanks for the bug report.

Should be fixed in https://github.com/podverse/podverse-web/pull/876
