### ISSUE TITLE
No connection or weak connection warning

### ISSUE THREAD

**Issue by tekmetal21** [podverse/podverse-web#895]
**Describe the bug**
No matter whether I'm connected to proper WiFi, hotspot, or using cellular, my android version of podverse says weak or no connection to the internet. It all started with the last update. I found a new update from yesterday, Ver. 4.6.2 build 1085. I cannot sign in and it cleared out all of my subscribed podcasts along with the downloaded and queued episodes.

**To Reproduce**
1. Go to 'Log In' from menu
2. Enter 'account credentials'
3. Click on 'Log In'

**Expected behavior**
Account log in, pulls my saved information and access my episodes 

**Screenshots**
![Screenshot_20220816-225713](https://user-images.githubusercontent.com/30637747/185024739-6dd2bf31-897a-4992-ad49-4d548c97e293.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 4a (5G)]
 - OS: [Android 12, July 5th update]
 - Browser [firefox]
 - Version [4.6.2 build 1085]

**Additional context**
It erased all of my local data after trying to log in.

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment]
@tekmetal21 thanks for the bug report. It's no problem but this is actually the website repo. The repo you're looking for is https://github.com/podverse/podverse-rn for the mobile app.

In any case...I hate to say it, but could you try deleting and reinstalling the app, then try signing in again? We replaced the secure storage library in the mobile app (the previous one hadn't been updated in two years, so we switched to a currently maintained one), and it seems like the migration is not working on all devices.

Please let us know if that does or doesn't work for you, and we'll take it from there.

**Comment by VKEERTHIVIKRAM** [comment]
I had the same issue. I cleared the AppData and then Logged in, and then it worked fine.

**Comment by tekmetal21** [comment]
> @tekmetal21 thanks for the bug report. It's no problem but this is actually the website repo. The repo you're looking for is https://github.com/podverse/podverse-rn for the mobile app.
> 
> In any case...I hate to say it, but could you try deleting and reinstalling the app, then try signing in again? We replaced the secure storage library in the mobile app (the previous one hadn't been updated in two years, so we switched to a currently maintained one), and it seems like the migration is not working on all devices.
> 
> Please let us know if that does or doesn't work for you, and we'll take it from there.

That is what I had to do, for some reason it didn't reload all of my subscribed podcasts. I ended up importing an older OPML and then manually subscribed to podcasts that weren't in that file. Also had to download all of my episodes again.

**Comment by tekmetal21** [comment]
> I had the same issue. I cleared the AppData and then Logged in, and then it worked fine.

I will try this if it happens again. Thank you for the suggestion.
