### ISSUE TITLE
Add support for transcripts with text/html format and no timestamps

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-web#961]
Requested by @genebene

This feed uses a transcript file in text/html format without any timestamps, which our transcript handler doesn't support yet.

https://feeds.buzzsprout.com/2053906.rss

https://feeds.buzzsprout.com/2053906/11416227/transcript

**Comment by genebean** [comment]
FWIW @mitchdowney, there’s a typo in my tagged name above. No biggie, just wanted you to know

**Comment by mitchdowney** [comment]
@genebean doh! I'll remember going forward :)

**Comment by mitchdowney** [comment]
@genebean this should be in v4.6.26

![image](https://user-images.githubusercontent.com/2262919/199634155-325aabfa-6e8d-43e3-ab0f-7ad65d8c6425.png)
